services:
  noway:
    build: .
    container_name: noway
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - generated_screenshots:/app/public/generated
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.noway.rule=Host(`noway.spaces.community`)"
      - "traefik.http.routers.noway.entrypoints=websecure"
      - "traefik.http.routers.noway.tls=true"
      - "traefik.http.routers.noway.tls.certresolver=letsencrypt"
      - "traefik.http.services.noway.loadbalancer.server.port=3000"

volumes:
  generated_screenshots:
